"""
NudgeEvent — a quality issue the interviewer should SPEAK (warmly), not
just log. The trigger is deterministic (engine.policy.nudge_policy); the
words are generated by the interviewer model in persona and folded into
the next utterance — never a separate turn (requirements §9).

Integrity issues (gaze, phone, second voice) are NOT nudges — they are
logged and surfaced in the report only.

STUB — landed in build-order pass 8 (nudge injector).
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class NudgeCategory(str, Enum):
    AUDIO_LOW = "audio_low"
    AUDIO_DEAD = "audio_dead"
    FACE_ABSENT = "face_absent"
    HEAD_POSE_OFF = "head_pose_off"
    VIDEO_FROZEN = "video_frozen"


class Severity(str, Enum):
    GENTLE = "gentle"
    DIRECT = "direct"


class NudgeEvent(BaseModel):
    category: NudgeCategory
    severity: Severity = Severity.GENTLE
    deferred: bool = True   # wait for a turn boundary (except AUDIO_DEAD)
